version: "3"

services:

  generate-funding-address:
    image: kinecosystem/payment-service
    command: pipenv run python generate_funding_address.py
    volumes:
      - .:/opt/app
    environment:
      STELLAR_HORIZON_URL: ${STELLAR_HORIZON_URL}
      STELLAR_NETWORK: ${STELLAR_NETWORK}
      STELLAR_KIN_ISSUER_ADDRESS: ${STELLAR_KIN_ISSUER_ADDRESS}
      STELLAR_KIN_TOKEN_NAME: ${STELLAR_KIN_TOKEN_NAME}
      STELLAR_INITIAL_XLM_AMOUNT: ${STELLAR_INITIAL_XLM_AMOUNT}
      KIN_FAUCET: ${KIN_FAUCET}
      XLM_FAUCET: ${XLM_FAUCET}
      OUTPUT_DIR: ./secrets
