version: "3"

services:

  generate-funding-address:
    image: kinecosystem/payment-service
    command: pipenv run python generate_funding_address.py
    volumes:
      - .:/opt/app
    environment:
      KIN_FAUCET: http://159.65.84.173:5000
      XLM_FAUCET: http://friendbot-kik.kininfrastructure.com
      STELLAR_HORIZON_URL: 'https://horizon-kik.kininfrastructure.com'
      STELLAR_NETWORK: 'private testnet'
      STELLAR_KIN_ISSUER_ADDRESS: 'GBQ3DQOA7NF52FVV7ES3CR3ZMHUEY4LTHDAQKDTO6S546JCLFPEQGCPK'
      STELLAR_KIN_TOKEN_NAME: 'KIN'
      OUTPUT_DIR: ./secrets
